exao_dap/registrar/urls.py
from django.urls import path, include
from rest_framework.generics import ListCreateAPIView
from . import views

urlpatterns = [
    # path('ingest/', views.ingest, name='registrar_ingest'),
    # path('verify_access/', views.verify_access, name='registrar_verify_access'),
    path('', views.overview, name='registrar_overview'),
]

exao_dap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

from rest_framework.authtoken import views as authtoken_views
from rest_framework import routers

from . import views
from . import signals  # ensure registration at startup
from .registrar import views as registrar_views

router = routers.SimpleRouter()
router.register(r'registrar/datasets', registrar_views.DatasetViewSet)
router.register(r'registrar/data', registrar_views.DatumViewSet)

admin.site.site_header = 'DAP administration'

urlpatterns = [
    path('', include(router.urls)),
    path('obtain-auth-token/', authtoken_views.obtain_auth_token),
    path('admin/', admin.site.urls),
    path('registrar/', include('exao_dap.registrar.urls')),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('', include('social_django.urls', namespace='social')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('users/me/', views.redirect_to_profile, name='redirect_to_profile'),
    path('users/<str:username>/', views.user_profile, name='user_profile'),
    path('', views.home, name='home'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)),]

exao_dap/registrar/models.py
import uuid
import os
from django.db import models
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import post_save
from django_q.tasks import async_task

from exao_dap_client import datum, dataset

from .. import cyverse, utils

# fyi iRODS collections can have really long names
MAX_SUPPORTED_PATH_LENGTH = 2048
MAX_IDENTIFIER_LENGTH = 128
HASH_LENGTH = 32  # md5 hexdigest
PATH_BASE = os.path.join(cyverse.IRODS_HOME, 'registrar')


class Dataset(models.Model):
    # storage
    identifier = models.CharField(
        max_length=MAX_IDENTIFIER_LENGTH,
        primary_key=True
    )

    # meta
    friendly_name = models.CharField(max_length=MAX_IDENTIFIER_LENGTH)
    description = models.TextField(blank=True, default='')
    source = models.CharField(max_length=10, choices=utils.enum_to_choices(dataset.DatasetSource))
    stage = models.CharField(max_length=10, choices=utils.enum_to_choices(dataset.DatasetStage))
    created_at = models.DateTimeField(auto_now_add=True)
    state = models.CharField(
        max_length=10,
        choices=utils.enum_to_choices(dataset.DatasetState),
        default=dataset.DatasetState.PENDING
    )

    # ways Datasets get made
    # grid = models.ForeignKey('undertaker.Grid', null=True)
    # bigjob = models.ForeignKey('undertaker.BigJob', null=True)
    source_path = models.CharField(max_length=MAX_SUPPORTED_PATH_LENGTH)

    # access control
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE, related_name='datasets_owned')
    # can be refreshed on demand from iRODS, should be done nightly or something
    shared = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='datasets_shared', blank=True)
    # dependencies = models.ManyToManyField(Dataset)  # for postprocessing products, obtainable through recursive walking of grids and bigjobs but as these should be R/O it is safe to denormalize
    public = models.BooleanField(default=False)

    def data_store_path(self):
        return f'irods://{cyverse.IRODS_HOST}' + os.path.join(PATH_BASE, self.identifier)

    def __str__(self):
        return self.data_store_path()

    def data_pending(self):
        return self.data.exclude(state=datum.DatumState.SYNCED)

    def data_synced(self):
        return self.data.filter(state=datum.DatumState.SYNCED)

    @classmethod
    def all_visible_to(cls, user):
        qs = cls.objects.filter(public=True)
        if user.is_authenticated and user.is_active:
            # superusers: everything
            if user.is_superuser or user.is_staff:
                return cls.objects.all()
            # normal users: things shared with them or owned by them
            return (qs |
                    cls.objects.filter(owner=user) |
                    cls.objects.filter(shared=user))
        return qs

    def is_visible_to(self, user):
        if self.public:
            return True
        elif user.is_authenticated and user.is_active:
            if user.is_superuser or user.is_staff:
                return True
            elif self.owner == user or user.datasets_shared.filter(pk=self.pk).exists():
                return True
        return False

    @classmethod
    def all_editable_by(cls, user):
        qs = cls.objects.all()
        if user.is_authenticated and user.is_active:
            # superusers: everything
            if user.is_superuser or user.is_staff:
                return cls.objects.all()
            # normal users: things shared with them or owned by them
            return cls.objects.filter(owner=user)
        return cls.objects.none()

    def is_editable_by(self, user):
        if user.is_authenticated and user.is_active:
            if user.is_superuser or user.is_staff:
                return True
            elif self.owner == user:
                return True
        return False



class Datum(models.Model):
    # want to copy in to service's storage area so backing files won't disappear, but should give read/ls access to original owner user
    filename = models.CharField(max_length=MAX_IDENTIFIER_LENGTH)
    checksum = models.CharField(max_length=HASH_LENGTH)
    size_bytes = models.PositiveBigIntegerField(verbose_name='size (bytes)')
    dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE, related_name='data')

    state = models.CharField(
        max_length=10,
        choices=utils.enum_to_choices(datum.DatumState),
        default=datum.DatumState.NEW
    )

    kind = models.CharField(max_length=20, choices=utils.enum_to_choices(datum.DatumKind))
    imported_at = models.DateTimeField(auto_now_add=True)
    # this should be inferred from metadata when available, otherwise use imported_at
    created_at = models.DateTimeField(null=True, blank=True)
    meta = models.JSONField(blank=True, default=dict)

    def data_store_path(self):
        return os.path.join(self.dataset.data_store_path(), self.filename)

    class Meta:
        constraints = (
            models.UniqueConstraint(
                fields=['dataset', 'filename'], name='unique_object_path'),
        )

    def __str__(self):
        return self.data_store_path()


@receiver(post_save, sender=Datum)
def launch_populate_metadata(sender, instance, **kwargs):
    if instance.state == datum.DatumState.NEW:
        async_task(
            'exao_dap.registrar.tasks.populate_metadata',
            instance.pk
        )

@receiver(post_save, sender=Datum)
def mark_dataset_complete(sender, instance, **kwargs):
    if instance.state == datum.DatumState.SYNCED:
        ds = instance.dataset
        remaining = ds.data_pending().count()
        if remaining == 0:
            ds.state = dataset.DatasetState.COMPLETE
            ds.save()

exao_dap/registrar/views.py
import os.path
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.db.models.fields import DateTimeField
from django.shortcuts import render
from django.http import JsonResponse, HttpResponseNotAllowed, HttpResponseRedirect
from django.urls import reverse
import fsspec
import irods_fsspec
from .filters import DatumFilter
from .forms import IngestPathVerifyForm, IngestForm
from .. import cyverse

from rest_framework import viewsets
from rest_framework.views import APIView
from rest_framework.decorators import action, permission_classes
from rest_framework.renderers import TemplateHTMLRenderer, JSONRenderer, BrowsableAPIRenderer
from rest_framework.permissions import IsAuthenticated
from rest_framework.decorators import renderer_classes
from rest_framework.response import Response
from .models import Dataset, Datum
from exao_dap_client import datum
from .serializers import DatasetSerializer, DatasetInitSerializer, DatumSerializer
from .. import extensions
from django_filters import rest_framework as filters
from rest_framework import permissions

class DatasetLimitOwnerSharedStaff(permissions.BasePermission):
    """
    Allow owner and staff/superuser to edit, additionally allow
    users with whom the dataset has been shared to read, and
    allow all to read if `public` is True
    """

    def has_object_permission(self, request, view, obj):
        # can_write = request.user.is_active and (
        #     request.user.is_staff or
        #     request.user.is_superuser or
        #     obj.owner == request.user
        # )
        # can_read = (
        #     can_write or
        #     (obj.public and obj.state == Dataset.DatasetState.COMPLETE) or
        #     (request.user.is_active and obj.shared.filter(username=request.user.username).exists())
        # )
        # GET, HEAD, or OPTIONS
        if request.method in permissions.SAFE_METHODS:
            return obj.is_visible_to(request.user)

        # POST, etc.
        return obj.is_editable_by(request.user)

class DatasetViewSet(extensions.BrowserFacingMixin, viewsets.ModelViewSet):
    serializer_class = DatasetSerializer
    queryset = Dataset.objects.all()
    permission_classes = [DatasetLimitOwnerSharedStaff]
    # renderer_classes = [TemplateHTMLRenderer, JSONRenderer]
    filterset_fields = {
        'identifier': ['exact', 'icontains']
    }

    def get_queryset(self):
        # unauthenticated: just public stuff
        qs = Dataset.objects.filter(public=True)
        if self.request.user.is_authenticated and self.request.user.is_active:
            # superusers: everything
            if self.request.user.is_superuser or self.request.user.is_staff:
                return self.queryset
            # normal users: things shared with them or owned by them
            return (qs |
                    Dataset.objects.filter(owner=self.request.user) |
                    Dataset.objects.filter(shared=self.request.user))
        return qs

    def retrieve(self, request, pk=None):
        if request.accepted_renderer.format != 'html':
            return super().retrieve(request)
        return Response({'object': self.get_object()})

    def create(self, request):
        if request.accepted_renderer.format == 'html':
            verify_form = None
            ingest_form = IngestForm(request.POST, user=request.user)
            if ingest_form.is_valid():
                # rearrange data, pass into serializer to create
                # (it will) launch ingest
                ser = DatasetInitSerializer(data=ingest_form.to_serializer_payload())
                ser.is_valid(raise_exception=True)
                obj = ser.save()
                return HttpResponseRedirect(reverse('dataset-detail', args=(obj.pk,)))
            return Response(
                {'verify_form': verify_form, 'ingest_form': ingest_form, 'source_path': ingest_form.cleaned_data['source_path']},
                template_name='registrar/ingest.html'
            )
        return super().create(request)

    @action(detail=False, methods=['GET'], renderer_classes=[TemplateHTMLRenderer])
    def ingest(self, request):
        if 'source_path' in request.GET:
            verify_form = IngestPathVerifyForm(request.GET)
            print(f'{verify_form.is_valid()=}')
            if not verify_form.is_valid():
                ingest_form = None
                path = request.GET['source_path']
            else:
                # path validated, on to step 2 (
                path = verify_form.cleaned_data['source_path']
                ingest_form = IngestForm(user=request.user, cleaned_irods_path=path)
                verify_form = None
        else:
            # Use unbound form when there is no param to validate
            verify_form = IngestPathVerifyForm()
            ingest_form = None
            path = None
        return Response(
            {'verify_form': verify_form, 'ingest_form': ingest_form, 'source_path': path},
            template_name='registrar/ingest.html'
        )


class DatumViewSet(extensions.BrowserFacingMixin, viewsets.ReadOnlyModelViewSet):
    serializer_class = DatumSerializer
    queryset = Datum.objects.all()
    # filterset_fields = ['kind', 'size_bytes', 'imported_at', 'created_at']
    filterset_class = DatumFilter
    # fields = {
    #     'kind': ['exact'],
    #     'size_bytes': ['lt', 'gt'],
    #     'imported_at': [
    # }
    filter_backends = (filters.DjangoFilterBackend,)
    def get_queryset(self):
        qs = Datum.objects.filter(dataset__public=True)
        if self.request.user.is_authenticated:
            qs = (qs |
                  Datum.objects.filter(dataset__owner=self.request.user) |
                  Datum.objects.filter(dataset__shared=self.request.user))
        return qs

    @action(
        detail=False, methods=['GET'],
        permission_classes=[IsAuthenticated]
    )
    def processing(self, request):
        # everywhere else, only SYNCED data are shown
        # dataset owners can see their data that's still being processed here
        # but otherwise only committed datasets are visible
        return Response(self.queryset.filter(
            dataset__owner=self.request.user,
            state__in=[datum.DatumState.SYNCING, datum.DatumState.NEW]
        ), template_name='datum_processing.html')

    def list(self, request):
        if request.accepted_renderer.format != 'html':
            return super().list(request)
        assert len(self.filter_backends) == 1

        queryset = self.filter_queryset(self.get_queryset())
        filterset = self.filter_backends[0]().get_filterset(request, queryset, self)
        context = {
            'object_list': queryset,
            'filterset': filterset,
        }
        page = self.paginate_queryset(queryset)
        if page is not None:
            context.update({'object_list': page})
        return render(request, 'datum_list.html', context)

@login_required
def overview(request):
    return render(request, 'registrar/overview.html')

exao_dap/registrar/templates/dataset_detail.html
{% extends "base.html" %}
{% block "content" %}
{% include 'registrar/dataset_snippet.html' %}
<table>
<thead>
<tr>
    <th>Filename</th>
    <th>Kind</th>
    <th>Created</th>
    <th>Imported</th>
</tr>
</thead>
<tbody>
{% for datum in object.data.all %}
<tr>
    <td>{{ datum.filename }}</td>
    <td>{{ datum.kind }}</td>
    <td>{% if datum.created_at %}{{ datum.created_at }}{% else %}&mdash;{% endif %}</td>
    <td>{{ datum.imported_at }}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endblock %}

exao_dap/registrar/templates/dataset_list.html
{% extends "base.html" %}
{% block "content" %}
<h1>Dataset</h1>
{% for object in object_list %}
{% include 'registrar/dataset_snippet.html' %}
{% empty %}
<h2>No data</h2>
{% endfor %}
{% endblock %}

exao_dap/registrar/templates/datum_list.html
{% extends "base.html" %}
{% block "title" %}Query data{% endblock "title" %}
{% block "container" %}
<div class="box has-background-warning-light content" style="height: 100%">
<h1>{% block "content_title" %}Query data{% endblock %}</h1>
<hr>
{% block "content" %}
{% if user.is_authenticated %}
<p>
    Data will be visible here if it belongs to your datasets or
    datasets that have been shared with you (including public datasets).
</p>

{% else %}
<p>Index of public data. Log in to ingest your own datasets and query datasets shared with you.</p>
{% endif %}
<style type="text/css" scoped>
ul#id_kind li {display: inline; }
</style>
<form method="get">
    {{ filterset.form.as_p }}
    <input class="button is-primary" type="submit" />
</form>
{% endblock %}
</div>
<div class="table-container">
<a class="button" href="{% url "datum-processing" %}">View your syncing data</a>
<table class="table is-fullwidth">
<thead>
<tr>
{% block "table-header" %}
    <th>Filename</th>
    <th>Dataset</th>
    <th>Source</th>
    <th>Stage</th>
    <th>Kind</th>
    <th>Created</th>
    <th>Imported</th>
{% endblock %}
</tr>
</thead>
<tbody>
{% for object in object_list %}
{% block "table-entry" %}
<tr>
    <td>{{ object.filename }}</td>
    <td><a href="{% url "dataset-detail" object.dataset.identifier %}">{{ object.dataset.identifier }}</a></td>
    <td>{{ object.dataset.source }}</td>
    <td>{{ object.dataset.stage }}</td>
    <td>{{ object.kind }}</td>
    <td>{{ object.created_at }}</td>
    <td>{{ object.imported_at }}</td>
</tr>
<tr><td colspan="7" class="px-5">{% include "registrar/meta_snippet.html" %}
</td></tr>
{% endblock %}
{% empty %}
<tr><td colspan="7"><div class="no-data"><div>
{% block "table-empty" %}
{% endblock %}
</div></div></td></tr>
{% endfor %}
</tbody>
</table>
</div>
{% endblock %}

exao_dap/registrar/templates/datum_processing.html
{% extends "datum_list.html" %}
{% block "title" %}Processing data{% endblock %}
{% block "content_title" %}Processing data{% endblock %}
{% block "content" %}
<p>Between creating the dataset through the web interface or API,
and it becoming available for queries and jobs, the platform must
index it to extract metadata.</p>
{% endblock %}
{% block "table-header" %}
    <th>State</th>
    <th>Filename</th>
    <th>Dataset</th>
    <th>Source</th>
    <th>Stage</th>
    <th>Kind</th>
    <th>Created</th>
    <th>Imported</th>
{% endblock %}
{% block "table-entry" %}
<tr>
    <td>{{ object.state }}</td>
    <td>{{ object.filename }}</td>
    <td><a href="{% url "dataset-detail" object.dataset.identifier %}">{{ object.dataset.identifier }}</a></td>
    <td>{{ object.dataset.source }}</td>
    <td>{{ object.dataset.stage }}</td>
    <td>{{ object.kind }}</td>
    <td>{{ object.created_at }}</td>
    <td>{{ object.imported_at }}</td>
</tr>
{% endblock %}
{% block "table-empty" %}
<h4>No data waiting to be ingested</h4>

{% endblock %}